<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <None Include="../../../../Források/3_Konyvek/csv/konyvek.csv" Link="konyvek.csv" CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>

</Project>
